services:
  - type: web
    name: unidiscovery-api-pn
    runtime: node
    plan: free
    region: singapore
    repo: https://github.com/Pranav-stac/unidiscovery-api
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api/v1
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: CORS_ORIGINS
        value: https://unidiscovery-web.vercel.app,https://unidiscovery-web-pranav-stacs-projects.vercel.app,http://localhost:3000
