import type { Prisma } from '@prisma/client';

/** Rich metadata keyed by career slug — merged at seed time */
export const CAREER_METADATA: Record<string, Prisma.InputJsonObject> = {
  'software-engineer': {
    educationPath: 'B.Tech CS / BS Computer Science → internships → SWE roles',
    typicalEntryRoutes: ['Campus placements', 'Internship conversion', 'Open-source portfolio', 'Competitive programming'],
    dayInTheLife: 'Write code, review PRs, debug production issues, collaborate in agile sprints.',
    regions: ['US', 'India', 'UK', 'Remote global'],
    workEnvironment: 'Office, hybrid, or fully remote; fast-paced product teams',
    requiredQualifications: ['Strong DSA', 'One systems language', 'Git & collaboration basics'],
    salaryNotes: 'Entry ₹6–18 LPA India; $90–140k US new grad at top firms',
    relatedMajors: ['Computer Science', 'Data Science', 'Information Technology'],
    skillsToBuildNow: ['Python or Java', 'Data structures', 'Personal projects on GitHub'],
    interviewTips: 'Practice LeetCode medium problems; explain trade-offs clearly in system design.',
  },
  doctor: {
    educationPath: 'PCB → NEET/MBBS (India) or A-Levels → MBBS (UK) → internship → specialization',
    typicalEntryRoutes: ['NEET rank', 'Medical school entrance', 'Graduate entry medicine (UK)'],
    dayInTheLife: 'Patient rounds, diagnoses, procedures, documentation, continuous learning.',
    regions: ['India', 'UK', 'US', 'Gulf'],
    workEnvironment: 'Hospitals, clinics, research labs; shift-based schedules',
    requiredQualifications: ['Biology & Chemistry mastery', 'Empathy', 'Long-term commitment'],
    salaryNotes: 'Resident stipends initially; senior consultants earn significantly more',
    relatedMajors: ['Medicine', 'Biomedical Sciences', 'Public Health'],
    skillsToBuildNow: ['Biology depth', 'Volunteer at clinics', 'Communication practice'],
    interviewTips: 'Demonstrate ethical reasoning and motivation beyond grades.',
  },
  'management-consultant': {
    educationPath: 'Top undergrad → case prep → MBB/D Big4 consulting',
    typicalEntryRoutes: ['Campus hiring', 'MBA pipeline', 'Experienced hire after 2–4 yrs industry'],
    dayInTheLife: 'Client meetings, data analysis, slide decks, problem structuring workshops.',
    regions: ['Global hubs: London, NYC, Mumbai, Singapore'],
    workEnvironment: 'Client site travel; high-intensity project cycles',
    requiredQualifications: ['Analytical thinking', 'Structured communication', 'Leadership evidence'],
    salaryNotes: '₹20–40 LPA entry India; $100k+ US analyst roles',
    relatedMajors: ['Economics', 'Engineering', 'Business'],
    skillsToBuildNow: ['Case interview practice', 'Excel/modeling', 'Debate & MUN'],
    interviewTips: 'Use MECE frameworks; practice mental math and market sizing.',
  },
  'product-designer': {
    educationPath: 'Design/ HCI degree or portfolio bootcamp → UX internship → product team',
    typicalEntryRoutes: ['Portfolio review', 'Design challenges', 'Internship projects'],
    dayInTheLife: 'User research, wireframes, prototypes, design critiques, ship with engineers.',
    regions: ['US', 'India', 'Europe', 'Remote'],
    workEnvironment: 'Cross-functional product squads; studio or remote',
    requiredQualifications: ['Portfolio (3–5 case studies)', 'Figma proficiency', 'User empathy'],
    salaryNotes: '₹8–25 LPA India; $80–130k US mid-level',
    relatedMajors: ['Design', 'HCI', 'Psychology + CS minor'],
    skillsToBuildNow: ['Redesign an app flow', 'Usability testing with peers', 'Design system basics'],
    interviewTips: 'Walk through process: problem → research → iterations → impact metrics.',
  },
  'data-scientist': {
    educationPath: 'Stats/Math/CS → projects & Kaggle → DS/ML roles',
    typicalEntryRoutes: ['ML internships', 'Analytics rotations', 'Research assistantships'],
    dayInTheLife: 'Clean data, build models, A/B tests, present insights to stakeholders.',
    regions: ['US', 'India', 'UK', 'Finance hubs'],
    workEnvironment: 'Tech, finance, healthcare analytics teams',
    requiredQualifications: ['Statistics', 'Python/R', 'SQL', 'Storytelling'],
    salaryNotes: 'Premium for ML/LLM specialization; ₹12–30 LPA India entry',
    relatedMajors: ['Data Science', 'Statistics', 'Computer Science'],
    skillsToBuildNow: ['Kaggle competitions', 'SQL + pandas', 'One end-to-end ML project'],
    interviewTips: 'Explain model choices, bias, and business impact—not just accuracy.',
  },
  'civil-engineer': {
    educationPath: 'B.Tech Civil → site/ design office → licensure (PE/IE)',
    typicalEntryRoutes: ['Campus placements', 'Government exams', 'Graduate trainee programs'],
    dayInTheLife: 'Site inspections, CAD drawings, project timelines, safety compliance.',
    regions: ['India infrastructure boom', 'UK green retrofit', 'Middle East projects'],
    workEnvironment: 'Construction sites + office; project travel common',
    requiredQualifications: ['Physics & math', 'AutoCAD basics', 'Safety awareness'],
    salaryNotes: 'Stable; senior project managers earn well in infra majors',
    relatedMajors: ['Civil Engineering', 'Structural Engineering'],
    skillsToBuildNow: ['AutoCAD/Revit intro', 'Intern with local contractor', 'Surveying basics'],
    interviewTips: 'Show project management examples and safety-first mindset.',
  },
  lawyer: {
    educationPath: 'LLB (India) / Law degree (UK) → bar exam → chambers or corporate law',
    typicalEntryRoutes: ['CLAT/LSAT', 'Training contracts (UK)', 'Litigation clerkships'],
    dayInTheLife: 'Research case law, draft contracts, client meetings, court appearances.',
    regions: ['India', 'UK', 'US', 'International arbitration hubs'],
    workEnvironment: 'Law firms, courts, in-house legal teams',
    requiredQualifications: ['Strong reading/writing', 'Logical argumentation', 'Ethics'],
    salaryNotes: 'Corporate law pays premium; litigation builds slowly',
    relatedMajors: ['Law', 'Political Science', 'Economics'],
    skillsToBuildNow: ['Debate', 'Legal reading', 'MUN & essay writing'],
    interviewTips: 'Demonstrate commercial awareness and structured legal reasoning.',
  },
  'teacher-educator': {
    educationPath: 'Subject degree → B.Ed / PGCE → classroom or EdTech',
    typicalEntryRoutes: ['Teacher training programs', 'International school hiring', 'EdTech content roles'],
    dayInTheLife: 'Lesson planning, classroom delivery, assessments, student mentoring.',
    regions: ['Global; strong demand in international schools'],
    workEnvironment: 'Schools, online platforms, curriculum teams',
    requiredQualifications: ['Subject mastery', 'Patience', 'Communication'],
    salaryNotes: 'Moderate in public sector; international schools pay better',
    relatedMajors: ['Education', 'Subject specialization + B.Ed'],
    skillsToBuildNow: ['Peer tutoring', 'Lesson plan samples', 'Classroom observation'],
    interviewTips: 'Teach a 10-minute demo lesson; show differentiation strategies.',
  },
  'machine-learning-engineer': {
    educationPath: 'CS/Stats MS or strong BS → ML internships → MLE roles',
    typicalEntryRoutes: ['Research internships', 'Kaggle + GitHub', 'ML bootcamps with projects'],
    dayInTheLife: 'Train models, deploy pipelines, monitor drift, optimize inference cost.',
    regions: ['US AI labs', 'India GCCs', 'Global remote'],
    workEnvironment: 'Research-heavy or product ML teams',
    requiredQualifications: ['Deep learning fundamentals', 'MLOps basics', 'Strong math'],
    salaryNotes: 'Top tier for LLM expertise; very competitive hiring',
    relatedMajors: ['AI/ML', 'Computer Science', 'Statistics'],
    skillsToBuildNow: ['PyTorch project', 'Deploy model with FastAPI', 'Read papers & reproduce'],
    interviewTips: 'Explain training pipeline end-to-end including failure modes.',
  },
  'cybersecurity-analyst': {
    educationPath: 'CS/Networking → Security+ / CEH → SOC or GRC roles',
    typicalEntryRoutes: ['Security internships', 'CTF competitions', 'IT support → security pivot'],
    dayInTheLife: 'Monitor alerts, investigate incidents, patch vulnerabilities, write reports.',
    regions: ['Global shortage; all industries hiring'],
    workEnvironment: 'SOC teams, consulting, in-house security',
    requiredQualifications: ['Networking basics', 'Linux', 'Security certifications help'],
    salaryNotes: 'Growing fast; cloud security commands premium',
    relatedMajors: ['Computer Science', 'Information Security'],
    skillsToBuildNow: ['TryHackMe paths', 'Home lab setup', 'CTF on HackTheBox'],
    interviewTips: 'Walk through how you would investigate a phishing incident.',
  },
  'ux-researcher': {
    educationPath: 'Psychology/HCI → UX research internship → product org',
    typicalEntryRoutes: ['Portfolio of research studies', 'Mixed methods projects', 'Design + research hybrid roles'],
    dayInTheLife: 'Plan studies, run interviews, synthesize insights, present to product teams.',
    regions: ['US tech', 'India product companies', 'Europe'],
    workEnvironment: 'Embedded in product squads',
    requiredQualifications: ['Research methods', 'Synthesis', 'Stakeholder communication'],
    salaryNotes: 'Growing demand in B2B SaaS and health tech',
    relatedMajors: ['Psychology', 'HCI', 'Anthropology'],
    skillsToBuildNow: ['5 user interviews on a app', 'Affinity mapping', 'Usability test report'],
    interviewTips: 'Present one research project with clear impact on product decisions.',
  },
  'investment-banker': {
    educationPath: 'Top econ/finance degree → spring week → analyst program',
    typicalEntryRoutes: ['Spring internships', 'Campus recruiting', 'MBA associate track'],
    dayInTheLife: 'Financial models, pitch books, client meetings, long hours on deals.',
    regions: ['London', 'NYC', 'Hong Kong', 'Mumbai'],
    workEnvironment: 'High-pressure deal teams',
    requiredQualifications: ['Financial modeling', 'Excel mastery', 'Resilience'],
    salaryNotes: 'High base + bonus; hours are intense',
    relatedMajors: ['Finance', 'Economics', 'Engineering + finance interest'],
    skillsToBuildNow: ['DCF model practice', 'Market news reading', 'Stock pitch deck'],
    interviewTips: 'Know recent deals; ace technicals and fit questions.',
  },
  'biomedical-engineer': {
    educationPath: 'B.Tech Biomedical → med-tech R&D or clinical engineering',
    typicalEntryRoutes: ['Med-tech internships', 'Research labs', 'Hospital clinical engineering'],
    dayInTheLife: 'Prototype devices, test biocompatibility, regulatory documentation.',
    regions: ['US med-tech', 'India growing startups', 'EU devices'],
    workEnvironment: 'R&D labs, hospitals, manufacturers',
    requiredQualifications: ['Biology + engineering', 'CAD', 'Regulatory awareness'],
    salaryNotes: 'Stable in established med-tech firms',
    relatedMajors: ['Biomedical Engineering', 'Mechanical + Biology'],
    skillsToBuildNow: ['Arduino biosensor project', 'CAD prosthetic concept', 'Lab safety training'],
    interviewTips: 'Discuss FDA/ISO awareness and interdisciplinary teamwork.',
  },
  'environmental-scientist': {
    educationPath: 'Environmental science degree → field/research → ESG or policy roles',
    typicalEntryRoutes: ['Field research assistant', 'ESG consulting internships', 'NGO programs'],
    dayInTheLife: 'Collect samples, analyze climate data, write impact reports for policy/clients.',
    regions: ['Global; EU regulation driving demand'],
    workEnvironment: 'Field + office; consulting travel',
    requiredQualifications: ['GIS/data skills', 'Ecology basics', 'Report writing'],
    salaryNotes: 'Growing with ESG mandates in corporates',
    relatedMajors: ['Environmental Science', 'Geography', 'Chemistry'],
    skillsToBuildNow: ['GIS intro', 'Climate data project', 'Volunteer with green NGO'],
    interviewTips: 'Link science to real policy or corporate sustainability outcomes.',
  },
  architect: {
    educationPath: 'B.Arch (5 yr) → internship → licensure → practice',
    typicalEntryRoutes: ['Architecture school portfolio', 'Studio internships', 'Competitions'],
    dayInTheLife: 'Sketch concepts, BIM modeling, client presentations, site visits.',
    regions: ['India urban boom', 'UK sustainable design', 'Global starchitect firms'],
    workEnvironment: 'Design studios; project-based deadlines',
    requiredQualifications: ['Spatial design', 'BIM/CAD', 'Building codes awareness'],
    salaryNotes: 'Slow start; senior partners earn well',
    relatedMajors: ['Architecture', 'Interior Design'],
    skillsToBuildNow: ['Sketch portfolio', 'Revit/SketchUp', 'Visit buildings & analyze space'],
    interviewTips: 'Present portfolio narrating design intent and constraints.',
  },
  journalist: {
    educationPath: 'Journalism/mass comm or any degree + portfolio → newsroom or digital media',
    typicalEntryRoutes: ['College paper', 'Internships', 'Independent newsletter/blog'],
    dayInTheLife: 'Research stories, interviews, write/edit, publish across formats.',
    regions: ['Digital media global', 'Legacy print declining'],
    workEnvironment: 'Newsrooms, freelance, creator economy',
    requiredQualifications: ['Writing', 'Ethics', 'Multimedia basics'],
    salaryNotes: 'Volatile freelance; established outlets more stable',
    relatedMajors: ['Journalism', 'English', 'Political Science'],
    skillsToBuildNow: ['Start blog/newsletter', 'Podcast episode', 'Fact-checking practice'],
    interviewTips: 'Bring clips showing investigation and clear narrative.',
  },
  pharmacist: {
    educationPath: 'B.Pharm → licensure exam → retail/clinical/hospital pharmacy',
    typicalEntryRoutes: ['Pharmacy college placements', 'Hospital residencies', 'Pharma industry QA'],
    dayInTheLife: 'Dispense medications, counsel patients, manage inventory, ensure compliance.',
    regions: ['India retail + hospital growth', 'US clinical pharmacy', 'UK NHS'],
    workEnvironment: 'Pharmacies, hospitals, pharma companies',
    requiredQualifications: ['Chemistry + biology', 'Attention to detail', 'Licensing exam'],
    salaryNotes: 'Stable; clinical roles pay more than retail over time',
    relatedMajors: ['Pharmacy', 'Pharmaceutical Sciences'],
    skillsToBuildNow: ['Shadow pharmacist', 'Drug interaction basics', 'Lab chemistry skills'],
    interviewTips: 'Emphasize patient safety and regulatory knowledge.',
  },
  'game-developer': {
    educationPath: 'CS/Game design → game jams → studio or indie',
    typicalEntryRoutes: ['Portfolio games', 'Game jams', 'QA → dev path'],
    dayInTheLife: 'Implement gameplay, optimize performance, collaborate with artists/designers.',
    regions: ['US AAA', 'India mobile gaming boom', 'Indie global'],
    workEnvironment: 'Studios; crunch culture in some AAA teams',
    requiredQualifications: ['C#/C++', 'Unity/Unreal', 'Math for games'],
    salaryNotes: 'Mobile F2P India hiring strongly; AAA pays premium',
    relatedMajors: ['Game Development', 'Computer Science'],
    skillsToBuildNow: ['Complete small Unity game', 'Game jam entry', 'Shader/math basics'],
    interviewTips: 'Demo a playable build; explain architecture and performance choices.',
  },
};

export const SUBJECT_METADATA: Record<string, Prisma.InputJsonObject> = {
  mathematics: {
    boards: ['CBSE', 'ICSE', 'IB HL', 'A-Level', 'IGCSE'],
    keyTopics: ['Algebra', 'Calculus', 'Statistics', 'Trigonometry', 'Probability'],
    relatedExams: ['JEE Main/Advanced', 'SAT Math', 'STEP', 'Olympiads'],
    difficultyTier: 'advanced',
    whyItMatters: 'Foundation for engineering, finance, data science, and logical reasoning everywhere.',
    studyTips: ['Daily problem practice', 'Understand proofs not just formulas', 'Use past papers under timed conditions'],
    prerequisiteSubjects: ['Arithmetic', 'Basic algebra'],
  },
  'computer-science': {
    boards: ['CBSE PCM+CS', 'IB CS', 'A-Level CS', 'AP CS A'],
    keyTopics: ['Programming', 'Algorithms', 'Data structures', 'Systems', 'Databases'],
    relatedExams: ['JEE', 'USACO', 'Codeforces', 'AP CS'],
    difficultyTier: 'intermediate',
    whyItMatters: 'Gateway to software, AI, cybersecurity, and digital product careers.',
    studyTips: ['Build projects weekly', 'Practice DSA consistently', 'Read others code on GitHub'],
    prerequisiteSubjects: ['Mathematics', 'Logic'],
  },
  biology: {
    boards: ['CBSE PCB', 'IB HL Biology', 'A-Level Biology'],
    keyTopics: ['Cell biology', 'Genetics', 'Human physiology', 'Ecology', 'Biotechnology'],
    relatedExams: ['NEET', 'BMAT', 'UCAT', 'Bio Olympiad'],
    difficultyTier: 'advanced',
    whyItMatters: 'Essential for medicine, biotech, environmental science, and research.',
    studyTips: ['Draw labeled diagrams', 'Link concepts across units', 'Practice NCERT thoroughly for NEET'],
    prerequisiteSubjects: ['Basic science', 'Chemistry'],
  },
  economics: {
    boards: ['CBSE Commerce', 'IB Economics', 'A-Level Economics'],
    keyTopics: ['Microeconomics', 'Macroeconomics', 'Market structures', 'Development economics'],
    relatedExams: ['CUET', 'Business school entrances', 'Economics Olympiad'],
    difficultyTier: 'intermediate',
    whyItMatters: 'Core for business, policy, finance, and consulting pathways.',
    studyTips: ['Read financial news daily', 'Practice graph analysis', 'Relate theory to real-world cases'],
    prerequisiteSubjects: ['Mathematics basics', 'English comprehension'],
  },
  'english-literature': {
    boards: ['CBSE English Core', 'IB Lang & Lit', 'A-Level English'],
    keyTopics: ['Literary analysis', 'Essay writing', 'Poetry & prose', 'Critical theory basics'],
    relatedExams: ['IELTS', 'TOEFL', 'Law entrances', 'Humanities applications'],
    difficultyTier: 'intermediate',
    whyItMatters: 'Critical for law, media, humanities, and strong communication in any career.',
    studyTips: ['Write one essay per week', 'Annotate texts deeply', 'Build vocabulary through reading'],
    prerequisiteSubjects: ['English language fundamentals'],
  },
  'art-design': {
    boards: ['CBSE Fine Arts', 'IB Visual Arts', 'A-Level Art & Design'],
    keyTopics: ['Drawing', 'Color theory', 'Design principles', 'Portfolio development'],
    relatedExams: ['NID entrance', 'NIFT', 'Architecture aptitude', 'Art school portfolios'],
    difficultyTier: 'intermediate',
    whyItMatters: 'Foundation for design, architecture, media, and creative technology roles.',
    studyTips: ['Maintain sketchbook daily', 'Document process not just outcomes', 'Seek critique regularly'],
    prerequisiteSubjects: ['Visual literacy', 'Optional math for architecture'],
  },
  physics: {
    boards: ['CBSE PCM', 'IB HL Physics', 'A-Level Physics'],
    keyTopics: ['Mechanics', 'Electricity & magnetism', 'Thermodynamics', 'Modern physics', 'Optics'],
    relatedExams: ['JEE Advanced', 'Physics Olympiad', 'ENGAA', 'SAT Physics'],
    difficultyTier: 'advanced',
    whyItMatters: 'Required for engineering, physics research, and strengthens quantitative reasoning.',
    studyTips: ['Solve numericals daily', 'Visualize problems with diagrams', 'Connect formulas to intuition'],
    prerequisiteSubjects: ['Mathematics', 'Basic mechanics concepts'],
  },
  'business-studies': {
    boards: ['CBSE Business Studies', 'IB BM', 'A-Level Business'],
    keyTopics: ['Marketing', 'Finance basics', 'Operations', 'Entrepreneurship', 'HR fundamentals'],
    relatedExams: ['CUET', 'BBA entrances', 'Case competitions'],
    difficultyTier: 'foundation',
    whyItMatters: 'Introduces commerce, entrepreneurship, and management thinking early.',
    studyTips: ['Analyze real company case studies', 'Participate in business competitions', 'Link chapters to news events'],
    prerequisiteSubjects: ['Basic mathematics', 'English'],
  },
};

export function withCareerMetadata<T extends { slug: string; metadata?: unknown }>(
  career: T,
): T & { metadata: Prisma.InputJsonValue } {
  const extra = CAREER_METADATA[career.slug] ?? {};
  return {
    ...career,
    metadata: { ...((career.metadata as Prisma.InputJsonObject) ?? {}), ...extra },
  };
}

export function withSubjectMetadata<T extends { slug: string; metadata?: unknown }>(
  subject: T,
): T & { metadata: Prisma.InputJsonValue } {
  const extra = SUBJECT_METADATA[subject.slug] ?? {};
  return {
    ...subject,
    metadata: { ...((subject.metadata as Prisma.InputJsonObject) ?? {}), ...extra },
  };
}
