/** Additional researched seed data — colleges, careers, activities, mentors */

export const expandedCollegesSeed = [
  {
    name: 'Carnegie Mellon University',
    country: 'United States',
    city: 'Pittsburgh',
    degree: 'BS',
    field: 'Computer Science & AI',
    description:
      'World leader in computer science, robotics, and artificial intelligence with strong industry pipelines to Google, Meta, and startups.',
    metadata: { fields: ['cs', 'ai', 'robotics', 'engineering'], avgGrade: 96, tags: ['STEM', 'AI', 'Research'] },
  },
  {
    name: 'University of California, Berkeley',
    country: 'United States',
    city: 'Berkeley',
    degree: 'BS',
    field: 'Engineering & Data Science',
    description:
      'Top public research university excelling in EECS, data science, and entrepreneurship in the Bay Area ecosystem.',
    metadata: { fields: ['cs', 'engineering', 'data', 'business'], avgGrade: 95, tags: ['STEM', 'Public Ivy'] },
  },
  {
    name: 'Georgia Institute of Technology',
    country: 'United States',
    city: 'Atlanta',
    degree: 'BS',
    field: 'Engineering & Computing',
    description:
      'Highly ranked for engineering, computing, and co-op programs with affordable in-state tuition and global reputation.',
    metadata: { fields: ['engineering', 'cs', 'math'], avgGrade: 93, tags: ['STEM', 'Co-op'] },
  },
  {
    name: 'University of Illinois Urbana-Champaign',
    country: 'United States',
    city: 'Urbana',
    degree: 'BS',
    field: 'Computer Science & Engineering',
    description:
      'Historic CS powerhouse (CS @ Illinois) with strong placements in software engineering and research.',
    metadata: { fields: ['cs', 'engineering', 'ai'], avgGrade: 92, tags: ['STEM', 'Research'] },
  },
  {
    name: 'University of Washington',
    country: 'United States',
    city: 'Seattle',
    degree: 'BS',
    field: 'Computer Science & Health Informatics',
    description:
      'Strong CS program adjacent to Amazon, Microsoft, and a growing health-tech corridor.',
    metadata: { fields: ['cs', 'health', 'data'], avgGrade: 91, tags: ['STEM', 'Tech Hub'] },
  },
  {
    name: 'University of Cambridge',
    country: 'United Kingdom',
    city: 'Cambridge',
    degree: 'BA',
    field: 'Natural Sciences & Engineering',
    description:
      'Collegiate university with rigorous Tripos system; world-class in mathematics, physics, and computer science.',
    metadata: { fields: ['science', 'math', 'engineering', 'humanities'], avgGrade: 97, tags: ['Russell Group', 'Research'] },
  },
  {
    name: 'Imperial College London',
    country: 'United Kingdom',
    city: 'London',
    degree: 'BEng/MEng',
    field: 'STEM & Medicine',
    description:
      'Science-focused institution specializing in engineering, computing, and medicine with strong industry links.',
    metadata: { fields: ['engineering', 'cs', 'medicine', 'science'], avgGrade: 96, tags: ['Russell Group', 'STEM'] },
  },
  {
    name: 'University College London',
    country: 'United Kingdom',
    city: 'London',
    degree: 'BSc',
    field: 'Multidisciplinary Sciences',
    description:
      'Large research university with strengths in computer science, economics, architecture, and global health.',
    metadata: { fields: ['cs', 'economics', 'architecture', 'health'], avgGrade: 94, tags: ['Russell Group', 'Global'] },
  },
  {
    name: 'London School of Economics',
    country: 'United Kingdom',
    city: 'London',
    degree: 'BSc',
    field: 'Economics & Social Sciences',
    description:
      'Premier institution for economics, finance, politics, and data science applications in policy and business.',
    metadata: { fields: ['economics', 'finance', 'politics', 'data'], avgGrade: 96, tags: ['Russell Group', 'Finance'] },
  },
  {
    name: 'University of Edinburgh',
    country: 'United Kingdom',
    city: 'Edinburgh',
    degree: 'BSc',
    field: 'Informatics & AI',
    description:
      'Pioneer in artificial intelligence research with strong informatics, linguistics, and data science programs.',
    metadata: { fields: ['ai', 'cs', 'linguistics', 'data'], avgGrade: 92, tags: ['Russell Group', 'AI'] },
  },
  {
    name: 'University of Manchester',
    country: 'United Kingdom',
    city: 'Manchester',
    degree: 'BSc',
    field: 'Engineering & Materials',
    description:
      'Major civic university with strengths in engineering, materials science, and computer science.',
    metadata: { fields: ['engineering', 'materials', 'cs'], avgGrade: 88, tags: ['Russell Group', 'Research'] },
  },
  {
    name: 'Indian Institute of Technology Delhi',
    country: 'India',
    city: 'New Delhi',
    degree: 'B.Tech',
    field: 'Engineering & Technology',
    description:
      'Top IIT for computer science, electrical engineering, and research with exceptional placement records.',
    metadata: { fields: ['engineering', 'cs', 'technology'], avgGrade: 94, tags: ['IIT', 'STEM'] },
  },
  {
    name: 'Indian Institute of Technology Madras',
    country: 'India',
    city: 'Chennai',
    degree: 'B.Tech',
    field: 'Engineering & Research',
    description:
      'Leading IIT known for engineering, data science initiatives, and strong startup incubation ecosystem.',
    metadata: { fields: ['engineering', 'cs', 'research'], avgGrade: 93, tags: ['IIT', 'STEM'] },
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    country: 'India',
    city: 'Kanpur',
    degree: 'B.Tech',
    field: 'Engineering & Sciences',
    description:
      'Research-intensive IIT with excellence in aerospace, mechanical, and computer science engineering.',
    metadata: { fields: ['engineering', 'aerospace', 'cs'], avgGrade: 92, tags: ['IIT', 'STEM'] },
  },
  {
    name: 'Birla Institute of Technology and Science, Pilani',
    country: 'India',
    city: 'Pilani',
    degree: 'B.E.',
    field: 'Engineering & Sciences',
    description:
      'Private deemed university with flexible dual degrees, strong CS placements, and study-abroad semester options.',
    metadata: { fields: ['engineering', 'cs', 'sciences'], avgGrade: 90, tags: ['Private', 'STEM'] },
  },
  {
    name: 'Vellore Institute of Technology',
    country: 'India',
    city: 'Vellore',
    degree: 'B.Tech',
    field: 'Engineering & Technology',
    description:
      'Large private university with international partnerships, strong industry connect, and diverse specializations.',
    metadata: { fields: ['engineering', 'cs', 'business'], avgGrade: 82, tags: ['Private', 'Industry'] },
  },
  {
    name: 'Manipal Academy of Higher Education',
    country: 'India',
    city: 'Manipal',
    degree: 'B.Tech',
    field: 'Health Sciences & Engineering',
    description:
      'Multi-disciplinary university excelling in medicine, engineering, and allied health with global student body.',
    metadata: { fields: ['health', 'engineering', 'sciences'], avgGrade: 85, tags: ['Private', 'Health'] },
  },
  {
    name: 'K J Somaiya Institute of Technology',
    country: 'India',
    city: 'Mumbai',
    degree: 'B.Tech',
    field: 'Engineering & AI',
    description:
      'Mumbai engineering college under Somaiya Vidyavihar with programs in AI, IT, and computer engineering.',
    metadata: { fields: ['engineering', 'ai', 'cs'], avgGrade: 80, tags: ['Mumbai', 'Engineering'] },
  },
  {
    name: 'University of British Columbia',
    country: 'Canada',
    city: 'Vancouver',
    degree: 'BSc',
    field: 'Computer Science & Forestry',
    description:
      'Top Canadian research university with strong CS, business, and environmental science programs.',
    metadata: { fields: ['cs', 'business', 'environment'], avgGrade: 90, tags: ['Canada', 'Research'] },
  },
  {
    name: 'McGill University',
    country: 'Canada',
    city: 'Montreal',
    degree: 'BSc',
    field: 'Sciences & Medicine',
    description:
      'Historic Montreal university renowned for medicine, neuroscience, and international student diversity.',
    metadata: { fields: ['medicine', 'science', 'neuroscience'], avgGrade: 92, tags: ['Canada', 'Medicine'] },
  },
  {
    name: 'University of Waterloo',
    country: 'Canada',
    city: 'Waterloo',
    degree: 'BCS',
    field: 'Computer Science & Co-op',
    description:
      'Global leader in co-operative education with elite computer science, math, and engineering programs.',
    metadata: { fields: ['cs', 'math', 'engineering'], avgGrade: 93, tags: ['Canada', 'Co-op', 'STEM'] },
  },
  {
    name: 'University of Sydney',
    country: 'Australia',
    city: 'Sydney',
    degree: 'Bachelor',
    field: 'Business & Engineering',
    description:
      'Australia\'s oldest university with strong business, engineering, and health sciences pathways.',
    metadata: { fields: ['business', 'engineering', 'health'], avgGrade: 88, tags: ['Australia', 'Go8'] },
  },
  {
    name: 'Australian National University',
    country: 'Australia',
    city: 'Canberra',
    degree: 'Bachelor',
    field: 'Policy & Sciences',
    description:
      'Research-intensive national university excelling in policy, computer science, and astrophysics.',
    metadata: { fields: ['policy', 'cs', 'science'], avgGrade: 91, tags: ['Australia', 'Research'] },
  },
  {
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    degree: 'BSc',
    field: 'Engineering & Informatics',
    description:
      'Europe\'s top technical university with low tuition, strong industry ties (BMW, Siemens), and English-taught programs.',
    metadata: { fields: ['engineering', 'cs', 'informatics'], avgGrade: 90, tags: ['Europe', 'STEM', 'Affordable'] },
  },
  {
    name: 'Delft University of Technology',
    country: 'Netherlands',
    city: 'Delft',
    degree: 'BSc',
    field: 'Engineering & Design',
    description:
      'Leading Dutch TU with world-class aerospace, civil, and computer engineering; English-medium BSc options.',
    metadata: { fields: ['engineering', 'aerospace', 'design'], avgGrade: 89, tags: ['Europe', 'STEM'] },
  },
  {
    name: 'National University of Ireland, Galway',
    country: 'Ireland',
    city: 'Galway',
    degree: 'BSc',
    field: 'Biomedical & Computing',
    description:
      'Growing tech hub university with biomedical engineering, data analytics, and EU post-study work pathways.',
    metadata: { fields: ['biomedical', 'cs', 'data'], avgGrade: 82, tags: ['Europe', 'Tech Hub'] },
  },
  {
    name: 'Nanyang Technological University',
    country: 'Singapore',
    city: 'Singapore',
    degree: 'Bachelor',
    field: 'Engineering & Business',
    description:
      'Fast-rising Asian university with strong engineering, business, and AI research; gateway to APAC careers.',
    metadata: { fields: ['engineering', 'business', 'ai'], avgGrade: 93, tags: ['Asia', 'STEM'] },
  },
  {
    name: 'Hong Kong University of Science and Technology',
    country: 'Hong Kong',
    city: 'Hong Kong',
    degree: 'BSc',
    field: 'Business & Technology',
    description:
      'Elite Asian university for finance, computing, and entrepreneurship with strong mainland China connections.',
    metadata: { fields: ['finance', 'cs', 'business'], avgGrade: 94, tags: ['Asia', 'Finance'] },
  },
  {
    name: 'University of Auckland',
    country: 'New Zealand',
    city: 'Auckland',
    degree: 'Bachelor',
    field: 'Sciences & Engineering',
    description:
      'New Zealand\'s top university offering engineering, computer science, and health with post-study work visa options.',
    metadata: { fields: ['engineering', 'cs', 'health'], avgGrade: 85, tags: ['Oceania', 'STEM'] },
  },
  {
    name: 'Columbia University',
    country: 'United States',
    city: 'New York',
    degree: 'BA/BS',
    field: 'Ivy League & Engineering',
    description:
      'Ivy League institution in NYC with Fu Foundation engineering, strong finance, journalism, and CS programs.',
    metadata: { fields: ['engineering', 'finance', 'cs', 'humanities'], avgGrade: 97, tags: ['Ivy', 'NYC'] },
  },
];

export const expandedCareersSeed = [
  {
    slug: 'machine-learning-engineer',
    title: 'Machine Learning Engineer',
    category: 'Technology',
    description: 'Build and deploy ML models at scale — from recommendation systems to computer vision.',
    subjects: ['Computer Science', 'Mathematics', 'Statistics'],
    skills: ['Python', 'TensorFlow/PyTorch', 'MLOps'],
    salaryMin: 90000,
    salaryMax: 200000,
    salaryCurrency: 'USD',
    growthOutlook: 'Explosive growth driven by generative AI adoption across industries.',
    hiringTrends: ['LLM fine-tuning', 'MLOps roles', 'India AI hubs'],
    limitations: ['Math-heavy', 'Rapid tool evolution'],
    combinations: ['ML + Domain (health, finance)', 'CS + Statistics'],
    employers: ['Google DeepMind', 'OpenAI', 'NVIDIA', 'Flipkart', 'TCS AI'],
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    category: 'Technology',
    description: 'Protect organizations from cyber threats through monitoring, incident response, and hardening.',
    subjects: ['Computer Science', 'Networking', 'Mathematics'],
    skills: ['Security tools', 'Risk assessment', 'Incident response'],
    salaryMin: 65000,
    salaryMax: 140000,
    salaryCurrency: 'USD',
    growthOutlook: 'Critical shortage of talent globally; 30%+ growth projected.',
    hiringTrends: ['Cloud security', 'SOC analysts', 'GRC roles'],
    limitations: ['On-call stress', 'Certification requirements'],
    combinations: ['CS + Law (cyber law)', 'Networking + Cloud'],
    employers: ['CrowdStrike', 'Palo Alto Networks', 'Deloitte', 'CERT-In'],
  },
  {
    slug: 'ux-researcher',
    title: 'UX Researcher',
    category: 'Design',
    description: 'Understand user behavior through interviews, testing, and data to shape product decisions.',
    subjects: ['Psychology', 'Design', 'Human-Computer Interaction'],
    skills: ['User interviews', 'Usability testing', 'Synthesis'],
    salaryMin: 60000,
    salaryMax: 150000,
    salaryCurrency: 'USD',
    growthOutlook: 'Growing as companies invest in user-centered product development.',
    hiringTrends: ['B2B SaaS', 'Health tech', 'Fintech UX'],
    limitations: ['Stakeholder influence challenges', 'Qualitative bias'],
    combinations: ['Psychology + Design', 'CS + HCI'],
    employers: ['Google', 'Microsoft', 'Razorpay', 'Spotify', 'IDEO'],
  },
  {
    slug: 'investment-banker',
    title: 'Investment Banker',
    category: 'Finance',
    description: 'Advise corporations on mergers, acquisitions, and capital raising in fast-paced deal environments.',
    subjects: ['Economics', 'Finance', 'Mathematics'],
    skills: ['Financial modeling', 'Valuation', 'Presentation'],
    salaryMin: 100000,
    salaryMax: 250000,
    salaryCurrency: 'USD',
    growthOutlook: 'Cyclical but lucrative; India IB market expanding.',
    hiringTrends: ['ECM/DCM', 'Tech M&A', 'ESG advisory'],
    limitations: ['Extreme hours', 'High pressure', 'Competitive entry'],
    combinations: ['Finance + Law', 'Economics + Tech'],
    employers: ['Goldman Sachs', 'JP Morgan', 'Kotak IB', 'Barclays'],
  },
  {
    slug: 'biomedical-engineer',
    title: 'Biomedical Engineer',
    category: 'Health',
    description: 'Design medical devices, prosthetics, and diagnostic tools bridging engineering and biology.',
    subjects: ['Biology', 'Physics', 'Engineering'],
    skills: ['CAD', 'Biomechanics', 'Regulatory knowledge'],
    salaryMin: 60000,
    salaryMax: 120000,
    salaryCurrency: 'USD',
    growthOutlook: 'Strong growth with aging populations and med-tech innovation.',
    hiringTrends: ['Wearables', 'Imaging systems', 'India med-tech startups'],
    limitations: ['Regulatory hurdles', 'Long R&D cycles'],
    combinations: ['Engineering + Biology', 'CS + Health informatics'],
    employers: ['Medtronic', 'Siemens Healthineers', 'Philips', 'GE Healthcare'],
  },
  {
    slug: 'environmental-scientist',
    title: 'Environmental Scientist',
    category: 'Science',
    description: 'Study ecosystems, climate data, and sustainability to inform policy and corporate ESG strategy.',
    subjects: ['Biology', 'Chemistry', 'Geography'],
    skills: ['Data analysis', 'Field research', 'GIS'],
    salaryMin: 45000,
    salaryMax: 90000,
    salaryCurrency: 'USD',
    growthOutlook: 'Accelerating due to climate regulation and corporate sustainability mandates.',
    hiringTrends: ['ESG consulting', 'Carbon accounting', 'Renewable energy'],
    limitations: ['Field work', 'Policy-dependent funding'],
    combinations: ['Science + Policy', 'Data Science + Environment'],
    employers: ['UNEP', 'WWF', 'Deloitte Sustainability', 'Tata Sustainability'],
  },
  {
    slug: 'architect',
    title: 'Architect',
    category: 'Design',
    description: 'Design buildings and spaces balancing aesthetics, function, sustainability, and regulations.',
    subjects: ['Mathematics', 'Physics', 'Art & Design'],
    skills: ['CAD/BIM', 'Spatial design', 'Project coordination'],
    salaryMin: 50000,
    salaryMax: 110000,
    salaryCurrency: 'USD',
    growthOutlook: 'Steady; green building and smart city projects driving new demand.',
    hiringTrends: ['Sustainable design', 'Urban planning', 'BIM specialists'],
    limitations: ['Long licensure path', 'Project timelines'],
    combinations: ['Architecture + Engineering', 'Design + Urban Planning'],
    employers: ['Foster + Partners', 'HOK', 'CP Kukreja', 'Somaya & Kalappa'],
  },
  {
    slug: 'journalist',
    title: 'Journalist / Media Professional',
    category: 'Media',
    description: 'Research, report, and communicate stories across print, digital, broadcast, and podcast media.',
    subjects: ['English', 'Political Science', 'History'],
    skills: ['Writing', 'Investigation', 'Multimedia production'],
    salaryMin: 35000,
    salaryMax: 90000,
    salaryCurrency: 'USD',
    growthOutlook: 'Digital and independent media growing; traditional print declining.',
    hiringTrends: ['Data journalism', 'Video content', 'Newsletter economy'],
    limitations: ['Deadline pressure', 'Income volatility in freelance'],
    combinations: ['Journalism + Data Science', 'English + Political Science'],
    employers: ['BBC', 'Reuters', 'The Hindu', 'New York Times', 'YouTube Creators'],
  },
  {
    slug: 'pharmacist',
    title: 'Pharmacist',
    category: 'Health',
    description: 'Dispense medications, counsel patients, and work in clinical, retail, or research pharmacy settings.',
    subjects: ['Chemistry', 'Biology', 'Pharmacy'],
    skills: ['Drug knowledge', 'Patient counseling', 'Regulatory compliance'],
    salaryMin: 90000,
    salaryMax: 140000,
    salaryCurrency: 'USD',
    growthOutlook: 'Stable demand; clinical pharmacy and pharma R&D growing in India.',
    hiringTrends: ['Clinical trials', 'Hospital pharmacy', 'Tele-pharmacy'],
    limitations: ['Licensing exams', 'Repetitive retail roles'],
    combinations: ['Pharmacy + MBA', 'Chemistry + Research'],
    employers: ['CVS Health', 'Apollo Pharmacy', 'Pfizer', 'NHS'],
  },
  {
    slug: 'game-developer',
    title: 'Game Developer',
    category: 'Technology',
    description: 'Create interactive games using engines like Unity/Unreal — gameplay, graphics, or tools programming.',
    subjects: ['Computer Science', 'Mathematics', 'Art'],
    skills: ['C#/C++', 'Game engines', '3D math'],
    salaryMin: 55000,
    salaryMax: 130000,
    salaryCurrency: 'USD',
    growthOutlook: 'Strong in mobile gaming (India) and AAA studios globally.',
    hiringTrends: ['Mobile F2P', 'Indie studios', 'VR/AR gaming'],
    limitations: ['Crunch culture', 'Competitive portfolio entry'],
    combinations: ['CS + Art (technical art)', 'Design + Programming'],
    employers: ['Ubisoft', 'EA', 'Dream11', 'Nazara', 'Rockstar'],
  },
];

const ActivityType = {
  COMPETITION: 'COMPETITION',
  INTERNSHIP: 'INTERNSHIP',
  SUMMER_PROGRAM: 'SUMMER_PROGRAM',
  PROJECT: 'PROJECT',
  VOLUNTEER: 'VOLUNTEER',
  OTHER: 'OTHER',
} as const;

export const expandedActivitiesSeed = [
  {
    title: 'Microsoft Explore Internship',
    type: ActivityType.INTERNSHIP,
    description: '12-week paid internship for first- and second-year students exploring software engineering at Microsoft.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['technology', 'cs', 'programming'],
    url: 'https://careers.microsoft.com/students/us/en/usuniversityexplore',
    metadata: { deadline: 'October', duration: '12 weeks', paid: true },
  },
  {
    title: 'Google STEP Internship',
    type: ActivityType.INTERNSHIP,
    description: 'Summer Trainee Engineering Program for first- and second-year undergraduates from underrepresented groups.',
    gradeMin: 13,
    gradeMax: 14,
    interests: ['technology', 'cs', 'diversity'],
    url: 'https://buildyourfuture.withgoogle.com/programs/step',
    metadata: { deadline: 'Fall', duration: '12 weeks', paid: true },
  },
  {
    title: 'Meta University Internship',
    type: ActivityType.INTERNSHIP,
    description: 'Engineering internship for students early in their CS journey with mentorship and real product work.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['technology', 'cs', 'social'],
    url: 'https://www.metacareers.com/students-and-grads',
    metadata: { deadline: 'Varies', duration: '12 weeks' },
  },
  {
    title: 'Jane Street INSIGHT Program',
    type: ActivityType.SUMMER_PROGRAM,
    description: 'Introductory program for women and underrepresented students interested in trading and technology.',
    gradeMin: 13,
    gradeMax: 14,
    interests: ['math', 'finance', 'technology'],
    url: 'https://www.janestreet.com/join-jane-street/programs-and-events/insight/',
    metadata: { deadline: 'Early year', duration: '1 week' },
  },
  {
    title: 'Research Science Institute (RSI)',
    type: ActivityType.SUMMER_PROGRAM,
    description: 'Highly selective six-week research program at MIT for talented high school students worldwide.',
    gradeMin: 11,
    gradeMax: 12,
    interests: ['research', 'science', 'math'],
    url: 'https://www.cee.org/programs/research-science-institute',
    metadata: { deadline: 'January', duration: '6 weeks', selective: true },
  },
  {
    title: 'Kaggle Competitions',
    type: ActivityType.COMPETITION,
    description: 'Global data science and ML competitions with real datasets — build portfolio and rankings.',
    gradeMin: 10,
    gradeMax: 16,
    interests: ['data', 'ai', 'programming'],
    url: 'https://www.kaggle.com/competitions',
    metadata: { deadline: 'Rolling', duration: 'Varies' },
  },
  {
    title: 'Smart India Hackathon',
    type: ActivityType.COMPETITION,
    description: 'National hackathon solving government and industry problems — strong resume builder for Indian students.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['technology', 'innovation', 'social-impact'],
    url: 'https://www.sih.gov.in/',
    metadata: { deadline: 'Annual', duration: '36 hours' },
  },
  {
    title: 'NASA OSTEM Internships',
    type: ActivityType.INTERNSHIP,
    description: 'Internships across NASA centers in engineering, science, and mission support for US and eligible students.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['aerospace', 'science', 'engineering'],
    url: 'https://stemgateway.nasa.gov/',
    metadata: { deadline: 'Rolling', duration: '10-16 weeks' },
  },
  {
    title: 'UN Volunteers Programme',
    type: ActivityType.VOLUNTEER,
    description: 'Online and on-site volunteering with UN agencies — gain global development experience.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['social-impact', 'policy', 'leadership'],
    url: 'https://www.unv.org/',
    metadata: { deadline: 'Rolling', duration: '3-12 months' },
  },
  {
    title: 'Coursera Guided Projects — Portfolio',
    type: ActivityType.PROJECT,
    description: 'Short hands-on projects in Python, SQL, ML, and cloud — stack credentials for internship applications.',
    gradeMin: 11,
    gradeMax: 16,
    interests: ['technology', 'data', 'self-learning'],
    url: 'https://www.coursera.org/projects',
    metadata: { deadline: 'Self-paced', duration: '1-3 hours each' },
  },
  {
    title: 'Y Combinator Startup School',
    type: ActivityType.SUMMER_PROGRAM,
    description: 'Free online program teaching startup fundamentals — ideal for entrepreneurial college students.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['entrepreneurship', 'business', 'technology'],
    url: 'https://www.startupschool.org/',
    metadata: { deadline: 'Rolling', duration: '7 weeks' },
  },
  {
    title: 'British Council GREAT Scholarships',
    type: ActivityType.OTHER,
    description: 'Scholarship pathway for Indian students applying to UK universities — research eligibility early.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['uk', 'scholarships', 'study-abroad'],
    url: 'https://www.britishcouncil.in/study-uk/scholarships',
    metadata: { deadline: 'Varies by university', duration: 'Annual cycle' },
  },
  {
    title: 'Fulbright-Nehru Fellowship',
    type: ActivityType.OTHER,
    description: 'Prestigious fellowship for Indian students pursuing masters or research in the United States.',
    gradeMin: 16,
    gradeMax: 16,
    interests: ['research', 'usa', 'study-abroad'],
    url: 'https://www.usief.org.in/',
    metadata: { deadline: 'May-June', duration: '1-2 years' },
  },
  {
    title: 'IEEE Student Branch Projects',
    type: ActivityType.PROJECT,
    description: 'Join your college IEEE chapter for robotics, embedded systems, and paper publication opportunities.',
    gradeMin: 13,
    gradeMax: 16,
    interests: ['engineering', 'robotics', 'research'],
    url: 'https://www.ieee.org/membership/students',
    metadata: { deadline: 'Campus-based', duration: 'Semester-long' },
  },
  {
    title: 'Codeforces Competitive Programming',
    type: ActivityType.COMPETITION,
    description: 'Regular algorithmic contests used by top tech companies for hiring — build rating over time.',
    gradeMin: 10,
    gradeMax: 16,
    interests: ['programming', 'algorithms', 'competitive'],
    url: 'https://codeforces.com/',
    metadata: { deadline: 'Weekly', duration: '2 hours per contest' },
  },
];

export const expandedMentorsSeed = [
  {
    name: 'Rohan Desai',
    field: 'AI & Data Science',
    company: 'Microsoft Research',
    country: 'India',
    bio: 'AI researcher from Mumbai engineering background. Guides students on MS applications, research internships, and ML portfolios.',
    expertise: ['AI/ML', 'MS applications', 'Research internships'],
  },
  {
    name: 'Lisa Thompson',
    field: 'Finance',
    company: 'Goldman Sachs',
    country: 'United Kingdom',
    bio: 'VP in investment banking with LSE economics background. Helps with finance careers, spring weeks, and CV prep.',
    expertise: ['Investment Banking', 'Spring internships', 'UK finance'],
  },
  {
    name: 'Dr. Ananya Krishnan',
    field: 'Medicine',
    company: 'AIIMS Delhi',
    country: 'India',
    bio: 'Resident physician who navigated NEET, MBBS, and specialization choices. Advises pre-med students across India.',
    expertise: ['NEET', 'Medical school', 'Specialization'],
  },
  {
    name: 'Marcus Johnson',
    field: 'Product Management',
    company: 'Stripe',
    country: 'United States',
    bio: 'PM from non-CS background who transitioned via internships and side projects. Coaches on PM interviews and storytelling.',
    expertise: ['Product Management', 'Career switch', 'Tech interviews'],
  },
  {
    name: 'Yuki Tanaka',
    field: 'Design',
    company: 'Sony Interactive',
    country: 'Japan',
    bio: 'Game UX designer with portfolio built through game jams and indie projects. Mentors on creative portfolios.',
    expertise: ['Game Design', 'UX Portfolio', 'Japan careers'],
  },
];
